# Generated by Django 5.2.8 on 2025-11-16 21:39

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("architects", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2025)),
                ("job_number", models.CharField(max_length=50, unique=True)),
                ("project_name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        help_text="Comma-separated types: M,E,P,EM,FP,TI,VI",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("closed_paid", "Closed & Paid"),
                            ("cancelled", "Cancelled / Voided"),
                            ("on_hold", "On Hold"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "current_sub_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("current_open_items", models.TextField(blank=True, null=True)),
                ("current_action_items", models.TextField(blank=True, null=True)),
                (
                    "due_date",
                    models.DateField(default=apps.projects.models.default_due_date),
                ),
                ("due_date_note", models.TextField(blank=True, null=True)),
                ("rough_in_date", models.DateField(blank=True, null=True)),
                ("rough_in_note", models.TextField(blank=True, null=True)),
                ("final_inspection_date", models.DateField(blank=True, null=True)),
                ("final_inspection_note", models.TextField(blank=True, null=True)),
                ("address", models.TextField()),
                (
                    "legal_address",
                    models.TextField(
                        blank=True, help_text="Parcel no, block no, lot no", null=True
                    ),
                ),
                ("billing_info", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_status_change", models.DateTimeField(auto_now_add=True)),
                (
                    "architect_designer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="architects.architect",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="clients.client"
                    ),
                ),
                (
                    "mechanical_manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "manager"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "job_number"],
            },
        ),
    ]
