# Generated by Django 5.2.8 on 2025-11-18 09:33

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="job_number",
            field=models.CharField(
                default=apps.projects.models.generate_job_number,
                editable=False,
                max_length=50,
                unique=True,
            ),
        ),
    ]
