# Generated by Django 5.2.8 on 2026-02-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_job_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.IntegerField(default=2026),
        ),
    ]
