# Generated by Django 5.2.8 on 2025-12-05 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_job_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('cc_emails', models.JSONField(blank=True, default=list, help_text='List of CC email addresses')),
                ('bcc_emails', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses')),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending'), ('bounced', 'Bounced'), ('delivered', 'Delivered')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, help_text='SES Message ID', max_length=200, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='projects.project')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='email_attachments/%Y/%m/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.emaillog')),
            ],
            options={
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for internal use', max_length=200)),
                ('template_type', models.CharField(choices=[('status_update', 'Status Update'), ('inspection_reminder', 'Inspection Reminder'), ('project_completion', 'Project Completion'), ('general_update', 'General Update'), ('invoice_notification', 'Invoice Notification'), ('delay_notification', 'Delay Notification'), ('custom', 'Custom Template')], max_length=50)),
                ('subject', models.CharField(help_text='Email subject. Use {{variable}} for dynamic content', max_length=300)),
                ('body_html', models.TextField(help_text='HTML email body. Use {{project.field_name}} for project data')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_variables', models.JSONField(blank=True, default=dict, help_text='JSON object documenting available variables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='communication.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['project', '-sent_at'], name='communicati_project_935637_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email', '-sent_at'], name='communicati_recipie_32d640_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='communicati_status_834ed7_idx'),
        ),
    ]
