# Generated by Django 5.2.8 on 2025-12-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("status_update", "Status Update"),
                    ("inspection_reminder", "Inspection Reminder"),
                    ("project_completion", "Project Completion"),
                    ("general_update", "General Update"),
                    ("invoice_notification", "Invoice Notification"),
                    ("delay_notification", "Delay Notification"),
                    ("permit_update", "Permit Update"),
                    ("custom", "Custom Template"),
                ],
                max_length=50,
            ),
        ),
    ]
