# Generated by Django 5.2.8 on 2026-02-19 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_archived_at_client_archived_by_and_more"),
        ("communication", "0002_alter_emailtemplate_template_type"),
        ("projects", "0003_alter_project_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail"),
                            ("outlook", "Outlook / Office 365"),
                            ("imap", "Custom IMAP"),
                        ],
                        default="imap",
                        max_length=20,
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[("password", "App Password"), ("oauth2", "OAuth 2.0")],
                        default="password",
                        max_length=20,
                    ),
                ),
                ("imap_host", models.CharField(blank=True, max_length=255)),
                ("imap_port", models.IntegerField(default=993)),
                ("imap_use_ssl", models.BooleanField(default=True)),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.IntegerField(default=587)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("password", models.CharField(blank=True, max_length=500)),
                ("oauth2_refresh_token", models.TextField(blank=True)),
                ("oauth2_access_token", models.TextField(blank=True)),
                ("oauth2_token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sync_enabled", models.BooleanField(default=True)),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=5, help_text="How often to sync in minutes"
                    ),
                ),
                (
                    "sync_folders",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IMAP folders to sync, e.g. ['INBOX', 'Sent']",
                    ),
                ),
                (
                    "max_sync_age_days",
                    models.IntegerField(
                        default=30,
                        help_text="Only sync emails newer than this many days",
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=20)),
                ("last_sync_error", models.TextField(blank=True)),
                ("total_synced", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
                "ordering": ["-created_at"],
                "unique_together": {("user", "email_address")},
            },
        ),
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                (
                    "participants",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses involved in the thread",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("unread_count", models.IntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("is_starred", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="communication.emailaccount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_threads",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_threads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Thread",
                "verbose_name_plural": "Email Threads",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder", models.CharField(max_length=200)),
                (
                    "uidvalidity",
                    models.BigIntegerField(
                        default=0,
                        help_text="IMAP UIDVALIDITY for detecting folder resets",
                    ),
                ),
                (
                    "last_uid",
                    models.BigIntegerField(default=0, help_text="Last synced IMAP UID"),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_cursors",
                        to="communication.emailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Cursor",
                "verbose_name_plural": "Sync Cursors",
            },
        ),
        migrations.CreateModel(
            name="SyncedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="RFC 2822 Message-ID header",
                        max_length=500,
                    ),
                ),
                ("imap_uid", models.CharField(blank=True, max_length=100)),
                ("folder", models.CharField(default="INBOX", max_length=200)),
                ("in_reply_to", models.CharField(blank=True, max_length=500)),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Message-IDs this email references",
                    ),
                ),
                ("from_address", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=200)),
                ("to_addresses", models.JSONField(default=list)),
                ("cc_addresses", models.JSONField(blank=True, default=list)),
                ("bcc_addresses", models.JSONField(blank=True, default=list)),
                ("reply_to", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=500)),
                ("date", models.DateTimeField(db_index=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="inbound",
                        max_length=10,
                    ),
                ),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "snippet",
                    models.CharField(
                        blank=True,
                        help_text="Short preview of the email body",
                        max_length=300,
                    ),
                ),
                ("has_attachments", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("is_draft", models.BooleanField(default=False)),
                ("raw_headers", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_emails",
                        to="communication.emailaccount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_emails",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_emails",
                        to="projects.project",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.emailthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synced Email",
                "verbose_name_plural": "Synced Emails",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SyncedEmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="synced_email_attachments/%Y/%m/"
                    ),
                ),
                ("is_inline", models.BooleanField(default=False)),
                ("content_id", models.CharField(blank=True, max_length=255)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="communication.syncedemail",
                    ),
                ),
            ],
            options={
                "ordering": ["file_name"],
            },
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["account", "-last_message_at"],
                name="communicati_account_f66f3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["project", "-last_message_at"],
                name="communicati_project_485259_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["client", "-last_message_at"],
                name="communicati_client__c0782e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="synccursor",
            unique_together={("account", "folder")},
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["account", "-date"], name="communicati_account_38e151_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["account", "folder", "-date"],
                name="communicati_account_f78839_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["from_address", "-date"], name="communicati_from_ad_c3d539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["direction", "-date"], name="communicati_directi_e18636_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["project", "-date"], name="communicati_project_494d6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["client", "-date"], name="communicati_client__b50b1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedemail",
            index=models.Index(
                fields=["is_read"], name="communicati_is_read_5f2dd5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncedemail",
            unique_together={("account", "message_id")},
        ),
    ]
