# Generated by Django 5.2.8 on 2026-01-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("outlook", "Microsoft Outlook / Office 365"),
                            ("gmail", "Gmail"),
                            ("custom", "Custom SMTP Server"),
                        ],
                        default="outlook",
                        max_length=20,
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        help_text="SMTP server hostname (auto-filled for known providers)",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        default=587, help_text="SMTP port (usually 587 for TLS)"
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, help_text="Use TLS encryption"),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Your email address for sending", max_length=254
                    ),
                ),
                (
                    "_email_password",
                    models.BinaryField(
                        blank=True, help_text="Encrypted app password", null=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Name to display as sender (e.g., 'John Smith')",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email settings have been verified",
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Settings",
                "verbose_name_plural": "Email Settings",
            },
        ),
    ]
