# Generated by Django 5.2.8 on 2025-11-16 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Architect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("professional_affiliations", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "architect"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="architect_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Architect/Designer",
                "verbose_name_plural": "Architects/Designers",
                "ordering": ["name"],
            },
        ),
    ]
