# Generated by Django 5.2.8 on 2025-11-16 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("note_added", "Note Added"),
                            ("field_updated", "Field Updated"),
                            ("inspection_scheduled", "Inspection Scheduled"),
                            ("due_date_changed", "Due Date Changed"),
                            ("project_created", "Project Created"),
                            ("project_updated", "Project Updated"),
                            ("client_changed", "Client Changed"),
                            ("architect_changed", "Architect Changed"),
                            ("manager_changed", "Manager Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "changed_field",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["project", "timestamp"],
                        name="activity_ac_project_bc6242_idx",
                    ),
                    models.Index(
                        fields=["action_type", "timestamp"],
                        name="activity_ac_action__9a6a36_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="activity_ac_user_id_89b464_idx",
                    ),
                ],
            },
        ),
    ]
