# Generated by Django 5.2.8 on 2025-12-28 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
        ("architects", "0001_initial"),
        ("clients", "0002_client_archived_at_client_archived_by_and_more"),
        ("projects", "0002_alter_project_job_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="architect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="architects.architect",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("client", "Client"),
                    ("architect", "Architect"),
                ],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status Change"),
                    ("note_added", "Note Added"),
                    ("field_updated", "Field Updated"),
                    ("inspection_scheduled", "Inspection Scheduled"),
                    ("due_date_changed", "Due Date Changed"),
                    ("project_created", "Project Created"),
                    ("project_updated", "Project Updated"),
                    ("client_changed", "Client Changed"),
                    ("architect_changed", "Architect Changed"),
                    ("manager_changed", "Manager Changed"),
                    ("client_created", "Client Created"),
                    ("client_updated", "Client Updated"),
                    ("client_archived", "Client Archived"),
                    ("client_restored", "Client Restored"),
                    ("architect_created", "Architect Created"),
                    ("architect_updated", "Architect Updated"),
                    ("architect_deactivated", "Architect Deactivated"),
                    ("architect_activated", "Architect Activated"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["entity_type", "timestamp"],
                name="activity_ac_entity__c451b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["client", "timestamp"], name="activity_ac_client__57544d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["architect", "timestamp"], name="activity_ac_archite_cb09d3_idx"
            ),
        ),
    ]
