# Generated by Django 5.2.8 on 2025-12-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_activitylog_architect_activitylog_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status Change"),
                    ("note_added", "Note Added"),
                    ("field_updated", "Field Updated"),
                    ("inspection_scheduled", "Inspection Scheduled"),
                    ("due_date_changed", "Due Date Changed"),
                    ("project_created", "Project Created"),
                    ("project_updated", "Project Updated"),
                    ("client_changed", "Client Changed"),
                    ("architect_changed", "Architect Changed"),
                    ("manager_changed", "Manager Changed"),
                    ("email_sent", "Email Sent"),
                    ("client_created", "Client Created"),
                    ("client_updated", "Client Updated"),
                    ("client_archived", "Client Archived"),
                    ("client_restored", "Client Restored"),
                    ("architect_created", "Architect Created"),
                    ("architect_updated", "Architect Updated"),
                    ("architect_deactivated", "Architect Deactivated"),
                    ("architect_activated", "Architect Activated"),
                ],
                max_length=50,
            ),
        ),
    ]
